use Mix.Config

config :frank,
  port: 4040,
  repo_root: "/var/opt/frank"

#config :frank,
#  repositories: [
#    #  "/home/gooose/src/other/complete/enter-haken/appointment",
#    #  "/home/gooose/src/other/complete/enter-haken/blog",
#    #  "/home/gooose/src/other/complete/enter-haken/cors_test",
#    #  "/home/gooose/src/other/complete/enter-haken/daysLeft",
#    #  "/home/gooose/src/other/complete/enter-haken/dotfiles",
#    #  "/home/gooose/src/other/complete/enter-haken/enter-haken.github.io",
#    #  "/home/gooose/src/other/complete/enter-haken/extjs-gen",
#    #  "/home/gooose/src/other/complete/enter-haken/hakyll-dot-demo",
#    #  "/home/gooose/src/other/complete/enter-haken/jsonutils",
#    #  "/home/gooose/src/other/complete/enter-haken/mongoscripts",
#    #  "/home/gooose/src/other/complete/enter-haken/mquery",
#    #  "/home/gooose/src/other/complete/enter-haken/plotTimeStamps",
#    #  "/home/gooose/src/other/complete/enter-haken/profanityChatLog",
#    #  "/home/gooose/src/other/complete/enter-haken/rasmus",
#    #  "/home/gooose/src/other/complete/enter-haken/reactBlogExample",
#    #  "/home/gooose/src/other/complete/enter-haken/SandcastleDemo",
#    #  "/home/gooose/src/other/complete/enter-haken/schema",
#    #  "/home/gooose/src/other/complete/enter-haken/scripts",
#    #  "/home/gooose/src/other/complete/enter-haken/VRRMonitor",
#    #  "/home/gooose/src/other/complete/enter-haken/xmlutils"
#
#    # "/home/gooose/src/other/complete/elixir-plug/plug",
#    # "/home/gooose/src/other/complete/elixir-plug/mime",
#    # "/home/gooose/src/other/complete/elixir-plug/plug_cowboy",
#    # "/home/gooose/src/other/complete/elixir-lang/elixir"
#    # "/home/jan.hake/src/lb/sw/cfb_rabbit_docker",
#    # "/home/jan.hake/src/lb/sw/mgmtb_aws",
#    # "/home/jan.hake/src/lb/sw/apiomat_wowimodule",
#    # "/home/jan.hake/src/lb/sw/xsd_compile",
#    # "/home/jan.hake/src/lb/sw/gcs/cloudservice_cli",
#    # "/home/jan.hake/src/lb/sw/gcs/gateway_enrollment_service",
#    # "/home/jan.hake/src/lb/sw/gcs/global_key_service",
#    # "/home/jan.hake/src/lb/sw/gcs/labs",
#    # "/home/jan.hake/src/lb/sw/gcs/toolbox",
#    # "/home/jan.hake/src/lb/sw/gcs/cloud_services_web_app",
#    # "/home/jan.hake/src/lb/sw/kata",
#    # "/home/jan.hake/src/lb/sw/lsbl_lib_java",
#    # "/home/jan.hake/src/lb/sw/lsdl_lib_java",
#    # "/home/jan.hake/src/lb/sw/core_api/backend",
#    # "/home/jan.hake/src/lb/sw/core_api/foundation",
#    # "/home/jan.hake/src/lb/sw/core_api/android",
#    # "/home/jan.hake/src/lb/sw/service_client_java",
#    # "/home/jan.hake/src/lb/sw/management-backend/devbox",
#    # "/home/jan.hake/src/lb/sw/mgmtb",
#    # "/home/jan.hake/src/lb/sw/dmz_rabbit_docker",
#    # "/home/jan.hake/src/lb/sw/lemonbeat_software_device",
#    # "/home/jan.hake/src/lb/sw/cloud_services",
#    # "/home/jan.hake/src/lb/sw/wowi/cordova-plugin-app-preferences",
#    # "/home/jan.hake/src/lb/sw/wowi/wizard",
#    # "/home/jan.hake/src/lb/sw/aws_iot_rest",
#    # "/home/jan.hake/src/lb/sw/common/certificates",
#    # "/home/jan.hake/src/lb/sw/common/lsdl_xsd",
#    # "/home/jan.hake/src/lb/sw/common/meta-lemonbeat",
#    # "/home/jan.hake/src/lb/sw/gw/app/gateway-leg",
#    # "/home/jan.hake/src/lb/sw/gw/app/gateway-mdg",
#    # "/home/jan.hake/src/lb/sw/gw/tools/topology_migrator",
#    # "/home/jan.hake/src/lb/sw/gw/common/mdg-architecture",
#    # "/home/jan.hake/src/lb/customer_plattform/mockups",
#    # "/home/jan.hake/src/lb/customer_plattform/key_generator",
#    # "/home/jan.hake/src/lb/customer_plattform/generators",
#    # "/home/jan.hake/src/lb/customer_plattform/admin_site",
#    # "/home/jan.hake/src/lb/management-tools/dev-bootloader-client",
#    # "/home/jan.hake/src/lb/management-tools/lemonbeat-studio",
#    # "/home/jan.hake/src/lb/management-tools/sgtin-tool",
#    # "/home/jan.hake/src/lb/management-tools/rest_kms_wrapper",
#    # "/home/jan.hake/src/lb/management-tools/op-connector",
#    # "/home/jan.hake/src/lb/management-tools/testsuite-testcases",
#    # "/home/jan.hake/src/lb/management-tools/device-preparation",
#    # "/home/jan.hake/src/lb/management-tools/bash",
#    # "/home/jan.hake/src/lb/management-tools/lb-studio-configuration-examples",
#    # "/home/jan.hake/src/lb/management-tools/serial-device-flasher",
#    # "/home/jan.hake/src/lb/management-tools/sgtin-mac-rsa-creator",
#  ]

import_config "config.#{Mix.env()}.exs"
